### PR TITLE
Calculate minAddr, maxAddr only for 64-bit

### PR DESCRIPTION
**Pull request by RaMMicHaeL**

### CODE REVIEW

**Comment by tapcio** [comment]
This builds ? Because you use si.dwAllocationGranularity in Find*FreeRegion, and now si is not even declared.

**Comment by RaMMicHaeL** [comment]
Find*FreeRegion are no longer used for x86. https://github.com/TsudaKageyu/minhook/commit/f62d9124fcc9ed8133c239229c3b0d20260bb4d8

**Comment by tapcio** [comment]
Sorry, I not have seen that.

**Comment by TsudaKageyu** [comment]
Thank you for this good catch and fix!

**Pull request merged**
